# Generated by Django 4.2.13 on 2025-01-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('prefer_not', '不願透露')], max_length=10)),
                ('age_group', models.CharField(choices=[('under_18', '18 歲以下'), ('18_25', '18-25 歲'), ('26_35', '26-35 歲'), ('36_45', '36-45 歲'), ('above_46', '46 歲以上')], max_length=20)),
                ('education', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('usage_frequency', models.CharField(max_length=50)),
                ('device_used', models.TextField()),
                ('overall_experience', models.IntegerField()),
                ('suggestions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
